# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_resources', '0002_auto_20170604_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='client_resources.Client'),
            preserve_default=False,
        ),
    ]
