# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_resources', '0003_auto_20170604_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='client_resources.Client'),
        ),
    ]
